name: user
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you want to publish it

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^1.0.0  # Specify the version
  flutter_bloc: ^8.0.0  # Specify the version
  hydrated_bloc: ^8.0.0  # Specify the version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/
    - assets/icons/  # Include the icons folder if you use it
